name: school_track_front
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  ferry: ^0.14.2+1
  ferry_flutter: ^0.8.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^12.0.0
  gql_websocket_link: ^1.1.0
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  provider: ^6.0.5
  built_collection: ^5.1.1
  openapi_generator_annotations: ^4.13.1
  openapi:
    path: "dart_openapi_api"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  ferry_generator: ^0.8.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  openapi_generator: ^4.13.1

flutter:
  uses-material-design: true
